package com.hrpm.mapper;

import com.hrpm.entity.PerformanceMetric;
import com.hrpm.entity.PerformanceConfigurationModels.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import org.apache.ibatis.annotations.*;

@Mapper
public interface PerformanceConfigurationMapper {
    @Select("SELECT id, code, name, metric_type AS metricType, unit, score_method AS scoreMethod, score_config AS scoreConfig, description, status, version FROM perf_metric WHERE deleted=0 ORDER BY code") List<PerformanceMetric> listMetrics();
    @Select("SELECT id, code, name, metric_type AS metricType, unit, score_method AS scoreMethod, score_config AS scoreConfig, description, status, version FROM perf_metric WHERE id=#{id} AND deleted=0") PerformanceMetric findMetric(long id);
    @Select("SELECT id, code, name, metric_type AS metricType, unit, score_method AS scoreMethod, score_config AS scoreConfig, description, status, version FROM perf_metric WHERE code=#{code} AND deleted=0") PerformanceMetric findMetricByCode(String code);
    @Insert("INSERT INTO perf_metric (id,code,name,metric_type,unit,score_method,score_config,description,status) VALUES (#{id},#{code},#{name},#{metricType},#{unit},#{scoreMethod},#{scoreConfig},#{description},#{status})") int insertMetric(@Param("id") long id, @Param("code") String code, @Param("name") String name, @Param("metricType") String metricType, @Param("unit") String unit, @Param("scoreMethod") String scoreMethod, @Param("scoreConfig") String scoreConfig, @Param("description") String description, @Param("status") String status);
    @Update("UPDATE perf_metric SET name=#{name},metric_type=#{metricType},unit=#{unit},score_method=#{scoreMethod},score_config=#{scoreConfig},description=#{description},status=#{status},version=version+1 WHERE id=#{id} AND version=#{version} AND deleted=0") int updateMetric(@Param("id") long id, @Param("name") String name, @Param("metricType") String metricType, @Param("unit") String unit, @Param("scoreMethod") String scoreMethod, @Param("scoreConfig") String scoreConfig, @Param("description") String description, @Param("status") String status, @Param("version") int version);

    @Select("SELECT id,code,name,applicability_rule AS applicabilityRule,status,version FROM perf_scheme WHERE deleted=0 ORDER BY code") List<Scheme> listSchemes();
    @Select("SELECT id,code,name,applicability_rule AS applicabilityRule,status,version FROM perf_scheme WHERE id=#{id} AND deleted=0") Scheme findScheme(long id);
    @Select("SELECT id,code,name,applicability_rule AS applicabilityRule,status,version FROM perf_scheme WHERE code=#{code} AND deleted=0") Scheme findSchemeByCode(String code);
    @Insert("INSERT INTO perf_scheme (id,code,name,applicability_rule,status) VALUES (#{id},#{code},#{name},#{applicabilityRule},'ACTIVE')") int insertScheme(@Param("id") long id,@Param("code") String code,@Param("name") String name,@Param("applicabilityRule") String applicabilityRule);
    @Select("SELECT id,scheme_id AS schemeId,version_no AS versionNo,evaluation_stages AS evaluationStages,snapshot,status,version FROM perf_scheme_version WHERE scheme_id=#{schemeId} AND deleted=0 ORDER BY version_no DESC") List<SchemeVersion> listVersions(long schemeId);
    @Select("SELECT id,scheme_id AS schemeId,version_no AS versionNo,evaluation_stages AS evaluationStages,snapshot,status,version FROM perf_scheme_version WHERE id=#{id} AND deleted=0") SchemeVersion findVersion(long id);
    @Insert("INSERT INTO perf_scheme_version (id,scheme_id,version_no,evaluation_stages,snapshot,status) VALUES (#{id},#{schemeId},#{versionNo},#{evaluationStages},#{snapshot},'DRAFT')") int insertVersion(@Param("id") long id,@Param("schemeId") long schemeId,@Param("versionNo") int versionNo,@Param("evaluationStages") String evaluationStages,@Param("snapshot") String snapshot);
    @Update("UPDATE perf_scheme_version SET evaluation_stages=#{evaluationStages},snapshot=#{snapshot},version=version+1 WHERE id=#{id} AND status='DRAFT' AND version=#{version} AND deleted=0") int updateVersion(@Param("id") long id,@Param("evaluationStages") String evaluationStages,@Param("snapshot") String snapshot,@Param("version") int version);
    @Update("UPDATE perf_scheme_version SET status='ENABLED',version=version+1 WHERE id=#{id} AND status='DRAFT' AND version=#{version} AND deleted=0") int enableVersion(@Param("id") long id,@Param("version") int version);
    @Select("SELECT id,scheme_version_id AS schemeVersionId,metric_id AS metricId,weight,score_method AS scoreMethod,score_config AS scoreConfig,sort_no AS sortNo,version FROM perf_scheme_item WHERE scheme_version_id=#{versionId} AND deleted=0 ORDER BY sort_no") List<SchemeItem> listItems(long versionId);
    @Insert("INSERT INTO perf_scheme_item (id,scheme_version_id,metric_id,weight,score_method,score_config,sort_no) VALUES (#{id},#{versionId},#{metricId},#{weight},#{scoreMethod},#{scoreConfig},#{sortNo})") int insertItem(@Param("id") long id,@Param("versionId") long versionId,@Param("metricId") long metricId,@Param("weight") BigDecimal weight,@Param("scoreMethod") String scoreMethod,@Param("scoreConfig") String scoreConfig,@Param("sortNo") int sortNo);
    @Delete("UPDATE perf_scheme_item SET deleted=1 WHERE scheme_version_id=#{versionId} AND deleted=0") int deleteItems(long versionId);
    @Select("SELECT id,scheme_version_id AS schemeVersionId,level_code AS levelCode,min_score AS minScore,max_score AS maxScore,include_min AS includeMin,include_max AS includeMax,version FROM perf_level_rule WHERE scheme_version_id=#{versionId} AND deleted=0 ORDER BY min_score") List<LevelRuleRow> listRules(long versionId);
    @Insert("INSERT INTO perf_level_rule (id,scheme_version_id,level_code,min_score,max_score,include_min,include_max) VALUES (#{id},#{versionId},#{levelCode},#{minScore},#{maxScore},#{includeMin},#{includeMax})") int insertRule(@Param("id") long id,@Param("versionId") long versionId,@Param("levelCode") String levelCode,@Param("minScore") BigDecimal minScore,@Param("maxScore") BigDecimal maxScore,@Param("includeMin") boolean includeMin,@Param("includeMax") boolean includeMax);
    @Delete("UPDATE perf_level_rule SET deleted=1 WHERE scheme_version_id=#{versionId} AND deleted=0") int deleteRules(long versionId);

    @Select("SELECT id,code,name,scheme_version_id AS schemeVersionId,start_date AS startDate,end_date AS endDate,self_deadline AS selfDeadline,manager_deadline AS managerDeadline,appeal_deadline AS appealDeadline,applicability_rule AS applicabilityRule,status,version FROM perf_cycle WHERE deleted=0 ORDER BY start_date DESC") List<Cycle> listCycles();
    @Select("SELECT id,code,name,scheme_version_id AS schemeVersionId,start_date AS startDate,end_date AS endDate,self_deadline AS selfDeadline,manager_deadline AS managerDeadline,appeal_deadline AS appealDeadline,applicability_rule AS applicabilityRule,status,version FROM perf_cycle WHERE id=#{id} AND deleted=0") Cycle findCycle(long id);
    @Select("SELECT id,code,name,scheme_version_id AS schemeVersionId,start_date AS startDate,end_date AS endDate,self_deadline AS selfDeadline,manager_deadline AS managerDeadline,appeal_deadline AS appealDeadline,applicability_rule AS applicabilityRule,status,version FROM perf_cycle WHERE code=#{code} AND deleted=0") Cycle findCycleByCode(String code);
    @Insert("INSERT INTO perf_cycle (id,code,name,scheme_version_id,start_date,end_date,self_deadline,manager_deadline,appeal_deadline,applicability_rule,status) VALUES (#{id},#{code},#{name},#{schemeVersionId},#{startDate},#{endDate},#{selfDeadline},#{managerDeadline},#{appealDeadline},#{applicabilityRule},'DRAFT')") int insertCycle(@Param("id") long id,@Param("code") String code,@Param("name") String name,@Param("schemeVersionId") long schemeVersionId,@Param("startDate") LocalDate startDate,@Param("endDate") LocalDate endDate,@Param("selfDeadline") LocalDateTime selfDeadline,@Param("managerDeadline") LocalDateTime managerDeadline,@Param("appealDeadline") LocalDateTime appealDeadline,@Param("applicabilityRule") String applicabilityRule);
    @Update("UPDATE perf_cycle SET status='STARTED',version=version+1 WHERE id=#{id} AND status='DRAFT' AND version=#{version} AND deleted=0") int startCycle(@Param("id") long id,@Param("version") int version);
    @Insert("INSERT INTO perf_task (id,cycle_id,employee_id,manager_employee_id,scheme_version_id,organization_snapshot,status) VALUES (#{id},#{cycleId},#{employeeId},#{managerEmployeeId},#{schemeVersionId},#{organizationSnapshot},'PENDING_SELF_ASSESSMENT')") int insertTask(@Param("id") long id,@Param("cycleId") long cycleId,@Param("employeeId") long employeeId,@Param("managerEmployeeId") Long managerEmployeeId,@Param("schemeVersionId") long schemeVersionId,@Param("organizationSnapshot") String organizationSnapshot);
    @Insert("INSERT INTO perf_task_item (id,task_id,metric_snapshot,weight,stage_snapshot) VALUES (#{id},#{taskId},#{metricSnapshot},#{weight},#{stageSnapshot})") int insertTaskItem(@Param("id") long id,@Param("taskId") long taskId,@Param("metricSnapshot") String metricSnapshot,@Param("weight") BigDecimal weight,@Param("stageSnapshot") String stageSnapshot);

    @Select("SELECT id,cycle_id AS cycleId,employee_id AS employeeId,manager_employee_id AS managerEmployeeId,scheme_version_id AS schemeVersionId,organization_snapshot AS organizationSnapshot,status,version FROM perf_task WHERE id=#{id} AND deleted=0") Task findTask(long id);
    @Select("SELECT t.id,t.cycle_id AS cycleId,t.employee_id AS employeeId,t.manager_employee_id AS managerEmployeeId,t.scheme_version_id AS schemeVersionId,t.organization_snapshot AS organizationSnapshot,t.status,t.version FROM perf_task t JOIN sys_user u ON u.employee_id=t.employee_id AND u.id=#{userId} AND u.deleted=0 WHERE t.deleted=0 ORDER BY t.created_time DESC") List<Task> listEmployeeTasks(long userId);
    @Select("SELECT id,cycle_id AS cycleId,employee_id AS employeeId,manager_employee_id AS managerEmployeeId,scheme_version_id AS schemeVersionId,organization_snapshot AS organizationSnapshot,status,version FROM perf_task WHERE manager_employee_id=#{managerEmployeeId} AND deleted=0 AND status='PENDING_MANAGER_SCORE' ORDER BY created_time") List<Task> listManagerTasks(long managerEmployeeId);
    @Select("SELECT id,cycle_id AS cycleId,employee_id AS employeeId,manager_employee_id AS managerEmployeeId,scheme_version_id AS schemeVersionId,organization_snapshot AS organizationSnapshot,status,version FROM perf_task WHERE cycle_id=#{cycleId} AND deleted=0 AND status='PENDING_PUBLISH'") List<Task> listPublishableTasks(long cycleId);
    @Select("SELECT id,task_id AS taskId,metric_snapshot AS metricSnapshot,weight,stage_snapshot AS stageSnapshot,version FROM perf_task_item WHERE task_id=#{taskId} AND deleted=0 ORDER BY id") List<TaskItem> listTaskItems(long taskId);
    @Select("SELECT id,task_item_id AS taskItemId,stage,evaluator_employee_id AS evaluatorEmployeeId,raw_score AS rawScore,weighted_score AS weightedScore,comment,version FROM perf_score WHERE task_item_id=#{taskItemId} AND deleted=0 ORDER BY created_time") List<Score> listScores(long taskItemId);
    @Select("SELECT id,task_item_id AS taskItemId,stage,evaluator_employee_id AS evaluatorEmployeeId,raw_score AS rawScore,weighted_score AS weightedScore,comment,version FROM perf_score WHERE task_item_id=#{taskItemId} AND stage=#{stage} AND evaluator_employee_id=#{employeeId} AND deleted=0") Score findScore(@Param("taskItemId") long taskItemId,@Param("stage") String stage,@Param("employeeId") long employeeId);
    @Insert("INSERT INTO perf_score (id,task_item_id,stage,evaluator_employee_id,raw_score,weighted_score,comment,submitted_time) VALUES (#{id},#{taskItemId},#{stage},#{employeeId},#{rawScore},#{weightedScore},#{comment},CURRENT_TIMESTAMP(3))") int insertScore(@Param("id") long id,@Param("taskItemId") long taskItemId,@Param("stage") String stage,@Param("employeeId") long employeeId,@Param("rawScore") BigDecimal rawScore,@Param("weightedScore") BigDecimal weightedScore,@Param("comment") String comment);
    @Update("UPDATE perf_task SET status=#{status},version=version+1 WHERE id=#{id} AND status=#{expectedStatus} AND version=#{version} AND deleted=0") int advanceTask(@Param("id") long id,@Param("expectedStatus") String expectedStatus,@Param("status") String status,@Param("version") int version);
    @Select("SELECT id,task_id AS taskId,current_version_no AS currentVersionNo,publish_status AS publishStatus,version FROM perf_result WHERE task_id=#{taskId} AND deleted=0") com.hrpm.entity.PerformanceConfigurationModels.Result findResult(long taskId);
    @Insert("INSERT INTO perf_result (id,task_id,current_version_no,publish_status) VALUES (#{id},#{taskId},1,'UNPUBLISHED')") int insertResult(@Param("id") long id,@Param("taskId") long taskId);
    @Insert("INSERT INTO perf_result_version (id,result_id,version_no,total_score,level_code,source,reason) VALUES (#{id},#{resultId},1,#{totalScore},#{levelCode},'MANAGER_SCORE',#{reason})") int insertResultVersion(@Param("id") long id,@Param("resultId") long resultId,@Param("totalScore") BigDecimal totalScore,@Param("levelCode") String levelCode,@Param("reason") String reason);
    @Select("SELECT id,result_id AS resultId,version_no AS versionNo,total_score AS totalScore,level_code AS levelCode,source,reason,published_time AS publishedTime FROM perf_result_version WHERE result_id=#{resultId} AND deleted=0 ORDER BY version_no DESC LIMIT 1") ResultVersion findLatestResultVersion(long resultId);
    @Update("UPDATE perf_result SET publish_status='PUBLISHED',version=version+1 WHERE id=#{id} AND publish_status='UNPUBLISHED' AND deleted=0") int publishResult(long id);
    @Update("UPDATE perf_result_version SET published_by=#{userId},published_time=CURRENT_TIMESTAMP(3) WHERE id=#{id} AND published_time IS NULL AND deleted=0") int markResultVersionPublished(@Param("id") long id,@Param("userId") long userId);
    @Update("UPDATE perf_cycle SET status='PUBLISHED',version=version+1 WHERE id=#{id} AND status='STARTED' AND version=#{version} AND deleted=0") int publishCycle(@Param("id") long id,@Param("version") int version);
}
