package com.hrpm.common;

import java.util.Map;

public final class ExceptionMessageLocalizer {
    private static final Map<String, String> EXACT_MESSAGES = Map.ofEntries(
            Map.entry("Invalid request", "请求参数不合法"),
            Map.entry("Username or password is invalid", "用户名或密码错误"),
            Map.entry("Session token is invalid or expired", "会话令牌无效或已过期"),
            Map.entry("The resource has changed. Refresh and try again.", "资源已发生变更，请刷新后重试"),
            Map.entry("Data scope denied", "当前账号无权访问该数据"),
            Map.entry("Workflow task is invalid", "工作流任务无效"),
            Map.entry("No matching workflow template is available", "未找到匹配的审批流程模板"),
            Map.entry("Leave request state does not allow this action", "当前请假单状态不允许执行该操作"),
            Map.entry("Leave balance is insufficient", "可用请假余额不足"),
            Map.entry("Parent Department does not exist", "上级部门不存在"),
            Map.entry("Month must use yyyy-MM format", "月份格式必须为 yyyy-MM"),
            Map.entry("New password must differ from current password", "新密码不能与当前密码相同"),
            Map.entry("Department code already exists", "部门编码已存在"),
            Map.entry("Department cannot be its own parent", "部门不能将自己设为上级部门"),
            Map.entry("Department cannot move under its descendant", "部门不能移动到自己的下级部门下"),
            Map.entry("Department has active child departments", "该部门下仍有启用中的子部门"),
            Map.entry("Department has active employees", "该部门下仍有在职员工"),
            Map.entry("Department leader is missing or inactive", "部门负责人不存在或已停用"),
            Map.entry("Parent department is inactive", "上级部门已停用"),
            Map.entry("Invalid department status", "部门状态不合法"),
            Map.entry("Invalid department version", "部门版本号不合法"),
            Map.entry("Invalid pagination", "分页参数不合法"),
            Map.entry("Employee not found", "员工不存在"),
            Map.entry("Employee number already exists", "员工编号已存在"),
            Map.entry("Employee account username already exists", "员工账号用户名已存在"),
            Map.entry("Department is missing or inactive", "部门不存在或已停用"),
            Map.entry("Position is missing or inactive", "岗位不存在或已停用"),
            Map.entry("Rank is missing or inactive", "职级不存在或已停用"),
            Map.entry("Employee cannot manage themselves", "员工不能将自己设置为直属上级"),
            Map.entry("Manager is missing or inactive", "直属上级不存在或已停用"),
            Map.entry("Invalid employment status", "任职状态不合法"),
            Map.entry("Invalid employee version", "员工版本号不合法"),
            Map.entry("Employee self-service role is unavailable", "员工自助角色当前不可用"),
            Map.entry("Leave type annual quota is not configured", "请假类型未配置年度额度"),
            Map.entry("Current user is not linked to an employee", "当前账号未关联员工"),
            Map.entry("Employee cannot create leave requests", "当前员工不能发起请假申请"),
            Map.entry("Leave type is unavailable", "请假类型不可用"),
            Map.entry("Leave end time must be after start time", "请假结束时间必须晚于开始时间"),
            Map.entry("Leave duration does not match the leave type minimum unit", "请假时长不符合该请假类型的最小申请单位"),
            Map.entry("Leave request is not available", "请假申请不存在或不可操作"),
            Map.entry("Invalid balance adjustment direction", "余额调整方向不合法"),
            Map.entry("Balance cannot be negative", "余额不能为负数"),
            Map.entry("Leave balance not found", "假期余额不存在"),
            Map.entry("Invalid leave balance version", "假期余额版本号不合法"),
            Map.entry("Leave request changed before approval", "请假申请已发生变更，无法完成审批"),
            Map.entry("Leave request changed before rejection", "请假申请已发生变更，无法完成驳回"),
            Map.entry("Leave request changed before return", "请假申请已发生变更，无法退回草稿"),
            Map.entry("Leave request is not in progress", "请假申请当前不在审批中"),
            Map.entry("Leave request changed before submission", "请假申请已发生变更，无法提交"),
            Map.entry("Leave request is not submittable", "请假申请当前不可提交"),
            Map.entry("Employee cannot submit leave requests", "当前员工不能提交请假申请"),
            Map.entry("Leave request overlaps an existing request", "请假时间与已有审批中或已通过的请假申请重叠"),
            Map.entry("Workflow instance changed before resubmission", "流程实例已发生变更，请刷新后重试"),
            Map.entry("Leave request changed before resubmission", "请假申请已发生变更，无法重新提交"),
            Map.entry("Unable to create workflow snapshot", "无法生成工作流快照"),
            Map.entry("Leave type code already exists", "请假类型编码已存在"),
            Map.entry("Leave type not found", "请假类型不存在"),
            Map.entry("Invalid leave type version", "请假类型版本号不合法"),
            Map.entry("Annual quota must be positive only for balance-deducting leave types", "只有扣减余额的请假类型才允许设置正数年度额度"),
            Map.entry("Unable to write operation audit log", "无法写入操作审计日志"),
            Map.entry("Unable to serialize audit summary", "无法序列化审计摘要"),
            Map.entry("Overtime end time must be after start time", "加班结束时间必须晚于开始时间"),
            Map.entry("Invalid overtime compensation type", "加班补偿方式不合法"),
            Map.entry("Overtime duration must be positive", "加班时长必须大于 0"),
            Map.entry("Overtime request version is stale", "加班申请版本已过期，请刷新后重试"),
            Map.entry("Overtime request is not cancellable", "当前加班申请不可撤销"),
            Map.entry("Time-off balance changed before cancellation", "调休余额已发生变更，请刷新后重试"),
            Map.entry("Overtime request changed before cancellation", "加班申请已发生变更，请刷新后重试"),
            Map.entry("Overtime request is not available", "加班申请不存在或不可操作"),
            Map.entry("Employee cannot create overtime requests", "当前员工不能发起加班申请"),
            Map.entry("Overtime request changed before approval", "加班申请已发生变更，无法完成审批"),
            Map.entry("Overtime request changed before rejection", "加班申请已发生变更，无法完成驳回"),
            Map.entry("Overtime request changed before return", "加班申请已发生变更，无法退回草稿"),
            Map.entry("Overtime request changed before submission", "加班申请已发生变更，无法提交"),
            Map.entry("Overtime request changed before resubmission", "加班申请已发生变更，无法重新提交"),
            Map.entry("Overtime request is not submittable", "加班申请当前不可提交"),
            Map.entry("Employee cannot submit overtime requests", "当前员工不能提交加班申请"),
            Map.entry("Personnel change can only be edited in draft", "人事异动只有在草稿状态下才能编辑"),
            Map.entry("Personnel change is not submittable", "人事异动当前不可提交"),
            Map.entry("Personnel change is not withdrawable", "人事异动当前不可撤回"),
            Map.entry("Workflow instance is not withdrawable", "当前流程实例不可撤回"),
            Map.entry("Workflow task changed before withdrawal", "工作流任务已发生变更，请刷新后重试"),
            Map.entry("Workflow instance changed before withdrawal", "流程实例已发生变更，请刷新后重试"),
            Map.entry("Only termination changes support handover items", "只有离职异动支持交接事项"),
            Map.entry("Handover items can only be edited before approval", "交接事项只能在审批通过前编辑"),
            Map.entry("Receiver employee is missing or inactive", "接收人不存在或已停用"),
            Map.entry("Exit handover item not found", "离职交接事项不存在"),
            Map.entry("Personnel change is not approved", "人事异动尚未审批通过"),
            Map.entry("Personnel change effective date has not been reached", "人事异动未到生效日期"),
            Map.entry("Required exit handover items are incomplete", "必填离职交接事项尚未完成"),
            Map.entry("Personnel change not found", "人事异动不存在"),
            Map.entry("Personnel change employee not found", "人事异动关联员工不存在"),
            Map.entry("Onboard change cannot reference an existing employee", "入职异动不能引用已有员工"),
            Map.entry("Employee number is required", "员工编号不能为空"),
            Map.entry("Employee name is required", "员工姓名不能为空"),
            Map.entry("Hire date is required", "入职日期不能为空"),
            Map.entry("Confirm change must set employment status to FORMAL", "转正异动必须将任职状态设置为正式"),
            Map.entry("Termination change must set employment status to TERMINATED", "离职异动必须将任职状态设置为离职"),
            Map.entry("Invalid personnel change type", "人事异动类型不合法"),
            Map.entry("Employment status is required", "任职状态不能为空"),
            Map.entry("Department is required", "部门不能为空"),
            Map.entry("Personnel change changed before withdrawal", "人事异动已发生变更，无法撤回"),
            Map.entry("Personnel change is not in progress", "人事异动当前不在审批中"),
            Map.entry("Personnel change changed before return", "人事异动已发生变更，无法退回草稿"),
            Map.entry("Exit handover not found", "离职交接单不存在"),
            Map.entry("Invalid version", "版本号不合法"),
            Map.entry("Invalid organization reference", "组织引用参数不合法"),
            Map.entry("Unable to parse personnel snapshot", "无法解析人事异动快照"),
            Map.entry("Unable to parse workflow snapshot", "无法解析工作流快照"),
            Map.entry("Unable to parse JSON content", "无法解析 JSON 内容"),
            Map.entry("Unable to serialize JSON content", "无法序列化 JSON 内容"),
            Map.entry("Position code already exists", "岗位编码已存在"),
            Map.entry("Rank code already exists", "职级编码已存在"),
            Map.entry("User not found", "用户不存在"),
            Map.entry("Role is missing or inactive", "角色不存在或已停用"),
            Map.entry("Invalid role ID", "角色 ID 不合法"),
            Map.entry("Work calendar not found", "工作日历不存在"),
            Map.entry("Work calendar year already exists", "该年度工作日历已存在"),
            Map.entry("Invalid work calendar status", "工作日历状态不合法"),
            Map.entry("Invalid work calendar time zone", "工作日历时区不合法"),
            Map.entry("Invalid work calendar day configuration", "工作日历日期配置不合法"),
            Map.entry("Invalid work calendar version", "工作日历版本号不合法"),
            Map.entry("Workflow task changed before approval", "工作流任务已发生变更，无法完成审批"),
            Map.entry("Workflow instance changed before approval", "流程实例已发生变更，无法完成审批"),
            Map.entry("Workflow instance not found", "工作流实例不存在"),
            Map.entry("Workflow task changed before rejection", "工作流任务已发生变更，无法完成驳回"),
            Map.entry("Workflow instance changed before rejection", "流程实例已发生变更，无法完成驳回"),
            Map.entry("Workflow task changed before return", "工作流任务已发生变更，无法退回"),
            Map.entry("Workflow instance changed before return", "流程实例已发生变更，无法退回"),
            Map.entry("Workflow task changed before transfer", "工作流任务已发生变更，无法转交"),
            Map.entry("Unable to create workflow task snapshot", "无法生成工作流任务快照"),
            Map.entry("Workflow template code and version already exist", "工作流模板编码和版本已存在"),
            Map.entry("Workflow template not found", "工作流模板不存在"),
            Map.entry("Workflow template contains an invalid approver rule", "工作流模板中的审批规则不合法"),
            Map.entry("Unsupported workflow template type or status", "工作流模板类型或状态不受支持"),
            Map.entry("Workflow scope department is missing or inactive", "工作流作用范围中的部门不存在或已停用"),
            Map.entry("Invalid workflow scope department ID", "工作流作用范围部门 ID 不合法"),
            Map.entry("Workflow nodes must be contiguous and use supported approver rules", "工作流节点必须连续编号且使用受支持的审批规则"),
            Map.entry("Approver rule type must match the workflow node type", "审批规则类型必须与工作流节点类型一致"),
            Map.entry("Specific approver user is missing or inactive", "指定审批人不存在或已停用"),
            Map.entry("Invalid workflow template version", "工作流模板版本号不合法"),
            Map.entry("JWT signing key must contain at least 32 characters", "JWT 签名密钥长度至少需要 32 个字符"),
            Map.entry("Invalid token subject", "令牌主体不合法"),
            Map.entry("Unable to sign session token", "无法签发会话令牌"),
            Map.entry("Performance scheme requires score items", "绩效方案必须包含评分项"),
            Map.entry("Performance scheme weights must total 100", "绩效方案权重总和必须为 100"),
            Map.entry("Performance level rules must map score exactly once", "绩效等级规则必须完整且唯一地覆盖分数区间"),
            Map.entry("Performance cycle requires an enabled scheme version", "绩效周期必须使用已启用的方案版本"),
            Map.entry("A metric can appear only once in a scheme version", "同一指标在方案版本中只能出现一次"),
            Map.entry("Scheme version can only use active metrics", "方案版本只能使用启用中的指标"),
            Map.entry("Level rule minimum cannot exceed maximum", "绩效等级规则的最小值不能大于最大值"),
            Map.entry("Performance level rules cannot overlap", "绩效等级规则不能重叠"),
            Map.entry("Performance scheme version requires items and level rules", "绩效方案版本必须包含评分项和等级规则"),
            Map.entry("Performance cycle dates are invalid", "绩效周期日期不合法")
    );

    private ExceptionMessageLocalizer() {
    }

    public static String localize(String message) {
        if (message == null || message.isBlank()) {
            return "系统处理失败，请稍后重试";
        }
        String localized = EXACT_MESSAGES.get(message);
        if (localized != null) {
            return localized;
        }
        if (message.startsWith("Duplicate workflow business handler: ")) {
            return "重复的工作流业务处理器：" + message.substring("Duplicate workflow business handler: ".length());
        }
        return message;
    }
}
