<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageFrame from '@/components/common/PageFrame.vue'
import EmptyState from '@/components/common/EmptyState.vue'
import { fetchManagerPerformanceTasks, fetchMyPerformanceTasks, submitManagerScore, submitSelfAssessment, type PerformanceTask } from '@/api/performance'

const mine = ref<PerformanceTask[]>([]); const manager = ref<PerformanceTask[]>([]); const loading = ref(false); const dialog = ref(false); const task = ref<PerformanceTask | null>(null); const mode = ref<'SELF' | 'MANAGER'>('SELF')
const scores = reactive<{ taskItemId: string; label: string; rawScore: number; comment: string }[]>([])
function metricName(snapshot: string) { try { const value = JSON.parse(snapshot); return value.name ?? value.code ?? '绩效指标' } catch { return '绩效指标' } }
async function load() { loading.value = true; try { [mine.value, manager.value] = await Promise.all([fetchMyPerformanceTasks(), fetchManagerPerformanceTasks()]) } catch { ElMessage.error('无法加载绩效任务') } finally { loading.value = false } }
function open(row: PerformanceTask, nextMode: 'SELF' | 'MANAGER') { task.value = row; mode.value = nextMode; scores.splice(0, scores.length, ...row.items.map((item) => ({ taskItemId: item.id, label: metricName(item.metricSnapshot), rawScore: 0, comment: '' }))); dialog.value = true }
async function submit() { if (!task.value || scores.some((item) => item.rawScore < 0)) return ElMessage.warning('请填写每项非负评分'); try { const payload = scores.map(({ taskItemId, rawScore, comment }) => ({ taskItemId, rawScore, comment })); if (mode.value === 'SELF') await submitSelfAssessment(task.value.id, task.value.version, payload); else await submitManagerScore(task.value.id, task.value.version, payload); ElMessage.success(mode.value === 'SELF' ? '自评已提交' : '评分已提交'); dialog.value = false; await load() } catch { ElMessage.error('提交失败，任务可能已被更新') } }
async function confirmSubmit() { try { await ElMessageBox.confirm('提交后本阶段评分将锁定，是否继续？', '确认提交', { type: 'warning' }); await submit() } catch { /* cancellation */ } }
onMounted(load)
</script>
<template><PageFrame title="绩效任务" description="完成个人自评、直属主管评分，并查看已发布的绩效结果。"><template #actions><el-button @click="load">刷新</el-button></template><el-tabs v-loading="loading"><el-tab-pane label="我的任务"><el-table :data="mine" class="data-table"><el-table-column prop="cycleName" label="考核周期" min-width="180"/><el-table-column prop="status" label="状态" width="190"/><el-table-column label="结果" width="140"><template #default="{ row }"><span v-if="row.publishStatus === 'PUBLISHED'">{{ row.totalScore }} / {{ row.levelCode }}</span><span v-else>未发布</span></template></el-table-column><el-table-column label="操作" width="130"><template #default="{ row }"><el-button v-if="row.status === 'PENDING_SELF_ASSESSMENT'" text type="primary" @click="open(row, 'SELF')">开始自评</el-button></template></el-table-column></el-table><EmptyState v-if="!loading && !mine.length" title="暂无绩效任务" description="考核周期启动后，任务会显示在这里。"/></el-tab-pane><el-tab-pane label="待我评分"><el-table :data="manager" class="data-table"><el-table-column prop="cycleName" label="考核周期" min-width="180"/><el-table-column prop="employeeName" label="员工" width="150"/><el-table-column prop="status" label="状态" width="190"/><el-table-column label="操作" width="130"><template #default="{ row }"><el-button text type="primary" @click="open(row, 'MANAGER')">评分</el-button></template></el-table-column></el-table><EmptyState v-if="!loading && !manager.length" title="暂无待评分任务" description="直属下属提交自评后会显示在这里。"/></el-tab-pane></el-tabs><el-dialog v-model="dialog" :title="mode === 'SELF' ? '填写自评' : '填写主管评分'" width="620"><el-form label-position="top"><el-form-item v-for="score in scores" :key="score.taskItemId" :label="score.label"><el-input-number v-model="score.rawScore" :min="0" :max="100"/><el-input v-model="score.comment" class="comment" placeholder="评分说明（可选）"/></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" @click="confirmSubmit">提交</el-button></template></el-dialog></PageFrame></template>
<style scoped>.comment{margin-top:8px}</style>
